spring.application.name=pxp-backend

server.port=8080

spring.datasource.url= ${DB_URL:jdbc:postgresql://localhost:5432/pxp_dev}
spring.datasource.username= ${DB_USER:postgres}
spring.datasource.password= ${DB_PASS:pxp-aziz}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.open-in-view= false

spring.flyway.enabled= true

pxp.cors.allowed-origins= ${CORS_ORIGINS:http://localhost:5173}

pxp.jwt.secret:${JWT_SECRET:projectsByTheProjectsBackendSecretToken}
pxp.jwt.expires-minutes: ${JWT_EXPIRES_MINUTES:240}

pxp.admin.username: ${PXP_ADMIN_USERNAME:pxp_Admin}
pxp.admin.password: ${PXP_ADMIN_PASSWORD:pxp_2020_password}
