spring.application.name=pxp-backend

server.port=8080

spring.datasource.url= ${DB_URL:jdbc:postgresql://localhost:5432/pxp_dev}
spring.datasource.username= ${DB_USER:postgres}
spring.datasource.password= ${DB_PASS:pxp-aziz}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.open-in-view= false

spring.flyway.enabled= true

pxp.cors.allowed-origins= ${CORS_ORIGINS:http://localhost:5173}

pxp.jwt.secret:${JWT_SECRET:projectsByTheProjectsBackendSecretToken}
pxp.jwt.expires-minutes: ${JWT_EXPIRES_MINUTES:240}

pxp.admin.username: ${PXP_ADMIN_USERNAME:pxp_Admin}
pxp.admin.password: ${PXP_ADMIN_PASSWORD:pxp_2020_password}

pxp.r2.account_id: ${R2_ACCOUNT_ID:b36f2f5279f498312f98fc45882494b9}
pxp.r2.bucket: ${R2_BUCKET:pxp-images}
pxp.r2.access-key: ${R2_ACCESS_KEY:1da8181b2e755478dcd18b0cd1b5804b}
pxp.r2.secret-key: ${R2_SECRET_KEY:5be4c596459b5e1b9d030d9de952235979b010e16bdf55ea1bc05e6c7ea9cd53}
pxp.r2.public-base-url: ${R2_PUBLIC_BASE_URL:https://pub-e6f6ce1a35864db081dcde5afca3219f.r2.dev}
pxp.r2.presign-minutes: ${R2_PRESIGN_MINUTES:15}
