spring.application.name=pxp-backend

server.port=8080

spring.datasource.url= ${DB_URL:jdbc:postgresql://localhost:5432/pxp_dev}
spring.datasource.username= ${DB_USER:postgres}
spring.datasource.password= ${DB_PASS:pxp-aziz}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.open-in-view= false

spring.flyway.enabled= true

pxp.cors.allowed-origins= ${CORS_ORIGINS:http://localhost:5173}